### ISSUE TITLE
[Bug]: Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ngoni** [OneSignal/OneSignal-Android-SDK#1789]
### What happened?

I installed v5.0.0-beta4 of the SDK, and noticed that I got the below crash report
The only thing i've done, is attempting to register for Push Notifications

### Steps to reproduce?

```Markdown
Install v5.0.0-beta4 of the SDK

I'm not sure what steps reproduce this issue but I'm hoping the crash report is sufficient
```

### What did you expect to happen?

No crash to happen

### OneSignal Android SDK version

Release 5.0.0-beta4

### Android version

13

### Specific Android models

```Markdown
Android Studio Emulator on Android 13
```

### Relevant log output

```Shell
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:42)
       at com.onesignal.core.internal.application.impl.ApplicationService.setCurrent(ApplicationService.kt:50)
       at com.onesignal.core.internal.application.impl.ApplicationService.onActivityStarted(ApplicationService.kt:145)
       at android.app.Application.dispatchActivityStarted(Application.java:401)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1404)
       at android.app.Activity.onStart(Activity.java:1922)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
       at android.app.Activity.performStart(Activity.java:8330)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @ngoni thank you for reaching out! 

A couple questions:

- Does this happen with a new installation of 5.0.0-beta4, or are you upgrading from a OneSignal major release version?
- Are there any other error messages you're seeing in the log for the device? 
- Have you tested with another device with the same results? 

Feel free to provide the entire device log; we'd be happy to take a look!

**Comment by ngoni** [comment]
Hi @jennantilla 

In response to your questions:

1. This happens with a new installation of 5.0.0-beta4. 
2. I don't have any information on this. I only saw that the SDK was crashing via Firebase Crashlytics reports.
3. No I haven't, but I'll actively start testing for this.

I'll continue monitoring the issue across multiple devices, and give you feedback if anything comes-up.

How far off is v5.0.0-beta SDK from being stable, as i'm looking to integrate it into our production app?

Should I rather use a more stable release?

Regards,
Ngoni

**Comment by jennantilla** [comment]
Hi @ngoni thanks for your patience! We have addressed this issue in our [latest major release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.0) of 5.0.0

Please update the SDK to this version and let us know if you are having any further issues.

**Comment by gapspt** [comment]
@jennantilla this issue persists in 5.0.2 (and I don't see it addressed in 5.0.3).
Either a regression, or not fixed at all, either way please reopen the issue.
Stacktrace from a production build:

```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.java:1)
       at com.onesignal.core.internal.application.impl.ApplicationService.setCurrent(ApplicationService.java:37)
       at com.onesignal.core.internal.application.impl.ApplicationService.onActivityStarted(ApplicationService.java:60)
       at android.app.Application.dispatchActivityStarted(Application.java:420)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1451)
       at android.app.Activity.onStart(Activity.java:1969)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
       at android.app.Activity.performStart(Activity.java:8616)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
```

**Comment by nan-li** [comment]
Hi @gapspt thanks for reaching out again, I apologize for any delay,

Our previous fix did not fix the issue. We have identified the cause and are working on the fix for all the methods this crash is reported. 

We have several other issues currently open about this crash, so do avoid duplicates, I'll keep this issue closed.
