### ISSUE TITLE
[Bug]: Don't show In-App after closed by back press

### ISSUE THREAD

**Issue by YKyrychenko** [OneSignal/OneSignal-Android-SDK#1826]
### What happened?

IAM not showing again after being closed by back button.

I have created IAM with "Every time trigger conditions are satisfied" option. It is working correctly, when I close IAM by software close button, it shows again when triggers in a correct state, but when I close it with hardware back button, there are no IAMs.

### Steps to reproduce?

```Markdown
1. Create full screen IAM with "Every time trigger conditions are satisfied" option selected. Add some custom triggers
2. Make conditions for triggering IAM
3. Wait for In-App to show
4. Close In-App by back button
5. Make conditions for triggering again
```

### What did you expect to happen?

IAM opens after being closed by back button

### OneSignal Android SDK version

4.8.6, 5.0.0

### Android version

11, 10

### Relevant log output

```Shell
2023-08-30 15:34:47.926 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  Triggers added: {my_video_page_open_trigger=11}
2023-08-30 15:34:47.926 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  Starting evaluateInAppMessages
2023-08-30 15:34:47.927 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  setDataForRedisplay: OSInAppMessage{messageId='78167909-e82f-4c9d-ab1a-63c6ee01876f', variants={all={default=e96595e0-ddbd-4b53-9e23-8b3b5dd13f91}}, triggers=[[OSTrigger{triggerId='1b7d043e-1e3c-4b75-bd39-be0cb8122977', kind=custom, property='profile_type', operatorType=equal, value=Adult_profile}, OSTrigger{triggerId='588ced24-ff17-4e12-8d23-94d8ece8bb6c', kind=custom, property='my_video_page_open_trigger', operatorType=greater, value=10}]], clickedClickIds=[], redisplayStats=OSInAppMessageDisplayStats{lastDisplayTime=1693398816, displayQuantity=3, displayLimit=2147483647, displayDelay=0}, displayDuration=0.0, displayedInSession=true, triggerChanged=true, actionTaken=false, isPreview=false, endTime=null, hasLiquid=false} triggerHasChanged: true
2023-08-30 15:34:47.927 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  OSInAppMessage lastDisplayTime: 1693398816 currentTimeInSeconds: 1693398887 diffInSeconds: 71 displayDelay: 0
2023-08-30 15:34:47.927 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  OSInAppMessage shouldDisplayAgain: true
2023-08-30 15:34:47.927 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  setDataForRedisplay message available for redisplay: 78167909-e82f-4c9d-ab1a-63c6ee01876f
2023-08-30 15:34:47.927 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  In app message with id: 78167909-e82f-4c9d-ab1a-63c6ee01876f, added to the queue
2023-08-30 15:34:47.929 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  displayFirstIAMOnQueue: [OSInAppMessage{messageId='78167909-e82f-4c9d-ab1a-63c6ee01876f', variants={all={default=e96595e0-ddbd-4b53-9e23-8b3b5dd13f91}}, triggers=[[OSTrigger{triggerId='1b7d043e-1e3c-4b75-bd39-be0cb8122977', kind=custom, property='profile_type', operatorType=equal, value=Adult_profile}, OSTrigger{triggerId='588ced24-ff17-4e12-8d23-94d8ece8bb6c', kind=custom, property='my_video_page_open_trigger', operatorType=greater, value=10}]], clickedClickIds=[], redisplayStats=OSInAppMessageDisplayStats{lastDisplayTime=1693398816, displayQuantity=3, displayLimit=2147483647, displayDelay=0}, displayDuration=0.0, displayedInSession=true, triggerChanged=true, actionTaken=false, isPreview=false, endTime=null, hasLiquid=false}]
2023-08-30 15:34:47.929 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  No IAM showing currently, showing first item in the queue!
2023-08-30 15:34:47.930 27348-28401 OneSignal               com.kyivstar.tv.mobile               D  OneSignalRestClient: Making request to: https://api.onesignal.com/in_app_messages/78167909-e82f-4c9d-ab1a-63c6ee01876f/variants/e96595e0-ddbd-4b53-9e23-8b3b5dd13f91/html?app_id=7ef3108d-4ea3-459b-9a10-6c2a3710f401
2023-08-30 15:34:48.016 27348-28401 OneSignal               com.kyivstar.tv.mobile               V  OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/in_app_messages/78167909-e82f-4c9d-ab1a-63c6ee01876f/variants/e96595e0-ddbd-4b53-9e23-8b3b5dd13f91/html?app_id=7ef3108d-4ea3-459b-9a10-6c2a3710f401
2023-08-30 15:34:48.016 27348-28401 OneSignal               com.kyivstar.tv.mobile               D  OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/in_app_messages/78167909-e82f-4c9d-ab1a-63c6ee01876f/variants/e96595e0-ddbd-4b53-9e23-8b3b5dd13f91/html?app_id=7ef3108d-4ea3-459b-9a10-6c2a3710f401
2023-08-30 15:34:48.021 27348-28401 OneSignal               com.kyivstar.tv.mobile               D  OneSignalRestClient: GET RECEIVED JSON: {"html":"\u003chtml\u003e\n\u003chead\u003e\u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover\"/\u003e\n\u003clink rel=\"preconnect\" href=\"https://fonts.googleapis.com\"\u003e\n\u003clink rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin\u003e\n\u003clink rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=System Font (Default)|System Font (Default)\"\u003e\n\u003cstyle\u003e\n    * {\n        -webkit-touch-callout: none;\n        -webkit-user-select: none; /* Disable selection/copy in UIWebView */\n    }\n\n    h1 {\n        font-weight: 400;\n    }\n\n    body {\n        font-family: -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif;\n        overflow: hidden;\n        cursor: pointer;\n        padding: 24px;\n        margin: 0;background-color: #FFFFFF;\n        \n    }\n\n    .flex-container {\n        display: flex;\n        flex-direction: column;\n        height: 100%;\n    }\n\n    /* top level elements */\n    .flex-container \u003e * {\n        margin-top: 8px;\n        margin-bottom: 8px;\n    }\n\n    /* Image only for Fullscreen and Modal */\n    .image-container {\n        display: flex;\n        justify-content: center;\n        flex-direction: column;\n    }\n\u003c/style\u003e\n\u003cscript\u003e\n    var iamInfo = {\n        location: \"full_screen\",\n        afterLoadCallbacks: [],\n        allowClicks: true,\n        shouldVerticalDragDismissMessage: true,\n        isRenderingComplete: false,\n    };\n    var bodyAction = {}\n\u003c/script\u003e\n\n\n    \u003cscript\u003e\n        bodyAction = {\"close\":false,\"prompts\":[],\"url_target\":\"browser\",\"id\":\"e291194a-31f4-4220-9894-0617556f0134\"}\n    \u003c/script\u003e\n\n\n\n\n\u003cscript\u003e\n    // Image src values and action urls are now encoded. \n    // Decode the value in DOMContentLoaded before resources are retrieved\n    function decodeURLs() {\n        var images = document.getElementsByClassName(\"iam-image\");\n        for (var i = 0, n = images.length; i \u003c n; i++) {\n            var imgElement = images[i];\n            var src = imgElement.getAttribute(\"src\");\n            imgElement.setAttribute(\"src\", decodeURIComponent(src.replace(/\\+/g, '%20')));\n        } \n\n        // Click Action URLs are now url encoded. Decode them and save to data-action-payload\n        var pageClickables = document.getElementsByClassName(\"iam-action-templatable\");\n        for (var i = 0, n = pageClickables.length; i \u003c n; i++) {\n            var el = pageClickables[i];\n            var attributes = getAttributes(el);\n            if (attributes[\"data-action-payload\"]) {\n                var dataActionPayload = attributes[\"data-action-payload\"]\n                var decodedActionPayload = decodeURIComponent(dataActionPayload.replace(/\\+/g, '%20'));\n                el.setAttribute(\"data-action-payload\", decodedActionPayload);\n            }\n        }\n    }\n\u003c/script\u003e\n\n\n\u003cscript\u003e\n    document.addEventListener(\"DOMContentLoaded\", decodeURLs);\n\u003c/script\u003e\n\n\n\u003cscript\u003e\n    // Called from onClick of images, buttons, and dismiss button\n    function actionTaken(data, clickType) {\n        console.log(\"actionTaken(): \" + JSON.stringify(data));\n        if (clickType)\n            data[\"click_type\"] = clickType;\n        postMessageToNative({ type: \"action_taken\", body: data });\n    }\n\n    function postMessageToNative(msgJson) {\n        console.log(\"postMessageToNative(): \" + JSON.stringify(msgJson));\n        var encodedMsg = JSON.stringify(msgJson);\n        postMessageToIos(encodedMsg);\n        postMessageToAndroid(encodedMsg);\n        postMessageToDashboard(encodedMsg);\n    }\n\n    function postMessageToIos(encodedMsg) {\n        // See iOS SDK Source\n        //    userContentControl
2023-08-30 15:34:48.021 27348-28401 OneSignal               com.kyivstar.tv.mobile               D  ler:didReceiveScriptMessage:\n        if (window.webkit \u0026\u0026 window.webkit.messageHandlers \u0026\u0026 window.webkit.messageHandlers.iosListener)\n            window.webkit.messageHandlers.iosListener.postMessage(encodedMsg);\n    }\n\n    function postMessageToAndroid(encodedMsg) {\n        if (window.OSAndroid)\n            window.OSAndroid.postMessage(encodedMsg);\n    }\n\n    function postMessageToDashboard(encodedMsg) {\n        if (window.parent) {\n            window.parent.postMessage(encodedMsg, \"*\");\n        }\n    }\n\n    // last-element needed to give the correct height for modals and banners\n    function getPageMetaData() {\n        var lastElement = document.getElementById(\"last-element\");\n        if (!lastElement)\n            return {};\n\n        var outerContentContainer = document.querySelector(\".outer-content-container\");\n        if (!outerContentContainer) {\n            console.error(\"Could not find outer-content-container class required to resize modal correctly!\");\n            return {};\n        }\n\n        // rect.y will be undefined on Android 4.4\n        var outerContentContainerRect = outerContentContainer.getBoundingClientRect();\n        return {\n            rect: {\n                height: lastElement.getBoundingClientRect().top + outerContentContainerRect.top\n            },\n            outerContentContainerRect: toJsonObject(outerContentContainerRect)\n        };\n    }\n\n    function toJsonObject(value) {\n        return JSON.parse(JSON.stringify(value));\n    }\n\n    function getAttributes(element) {\n        var attributes = {};\n        if (element.hasAttributes()) {\n            for (var i = 0, n = element.attributes.length; i \u003c n; i++) {\n                var attr = element.attributes[i];\n                attributes[attr.name] = attr.value;\n            }\n        }\n        return attributes;\n    }\n\n    // TODO: Remove after we have verified we are not seeing any mis touches.\n    // Just a quick and dirty way to see where you have tapped by moving the close button to where you tapped.\n    function debugTaps() {\n        document.body.addEventListener('click', function(e) {\n            console.log(\"body onlick:\" + JSON.stringify({x: e.pageX, y: e.pageY}));\n            document.querySelector(\".close-button\").style.display = \"block\";\n            document.querySelector(\".close-button\").style.right = 0;\n            document.querySelector(\".close-button\").style.left = e.pageX;\n            document.querySelector(\".close-button\").style.top = e.pageY;\n        }, true);\n    }\n\n    function standardBodyClick(e) {\n        e.stopPropagation();\n\n        if (iamInfo.allowClicks) {\n            \n                actionTaken(bodyAction, \"body\");\n            \n        }\n    }\n\n    window.onresize = function() {\n        postMessageToNative({\n            type: \"resize\",\n            pageMetaData: getPageMetaData(),\n            displayLocation: iamInfo.location\n        });\n    };\n\n    // Lets the SDK know the page is done loading as well as its display type and location\n    window.onload = function() {\n        // 1. Inform native code \"render_complete\" event fired\n        postMessageToNative({\n            type: \"rendering_complete\",\n            pageMetaData: getPageMetaData(),\n            displayLocation: iamInfo.location,\n            dragToDismissDisabled: !iamInfo.shouldVerticalDragDismissMessage,\n        });\n\n        // 2. Setup all action events for button clicks (body, button, image, \u0026 close)\n        // Body clicks\n        \n            document.addEventListener(\"click\", standardBodyClick, false);\n        \n\n        // Close button clicks\n        var closeButtons = document.querySelectorAll(\".close-button\");\n        closeButtons.forEach(closeButton =\u003e {\n            closeButton.addEventListener(\"click\", function(e) {\n            if (iamInfo.allowClicks) {\n                actionTaken({close: true});\n             
2023-08-30 15:34:48.021 27348-28401 OneSignal               com.kyivstar.tv.mobile               D     e.stopPropagation();\n            }\n            }, true);\n        });\n\n        // Image and Button clicks\n        var clickable = document.getElementsByClassName(\"iam-clickable\");\n        for (var i = 0, n = clickable.length; i \u003c n; i++) {\n            var el = clickable[i];\n            var attributes = getAttributes(el);\n            if (attributes[\"data-action-payload\"]) {\n                // use iife to close over the right element and value\n                (function(element, value, label) {\n                    element.addEventListener(\"click\", function(e) {\n                        if (iamInfo.allowClicks) {\n                            actionTaken(value, label);\n                            e.stopPropagation();\n                        }\n                    }, true);\n                })(el, JSON.parse(attributes[\"data-action-payload\"]), attributes[\"data-action-label\"]);\n            }\n        }\n\n        for (var i = 0, n = iamInfo.afterLoadCallbacks.length; i \u003c n; i++) {\n           iamInfo.afterLoadCallbacks[i]();\n        }\n    };\n\u003c/script\u003e\n\u003cstyle\u003e\n        \n        .flex-container {\n            align-content: center;\n            justify-content: space-around;\n            height: 100%;\n            \n        }\n\n        .image-container {\n            flex-basis: 100%;\n        }\n\n        .outer-content-container {\n            overflow-y: hidden;\n            overflow-x: hidden;\n        }\n\n        .pages-container {\n            height: 100%;\n        }\n\n        .pages-container .page {\n            background: inherit;\n            overflow: hidden;\n            height: 100%;\n        }\n\n        \n            #text-dcff8633-5845-4659-be32-3d15cbc7937c {\n  color: #222;\n  font-family: System Font (Default);\n  font-size: 24;\n  font-style: normal;\n  font-weight: normal;\n  margin-bottom: 0px;\n  margin-left: 0px;\n  margin-right: 0px;\n  margin-top: 0px;\n  text-align: center;\n  text-decoration: none;\n}\n#button-e76dd4e2-9354-4e3f-9a0c-2789c44afa0a {\n  font-family: System Font (Default);\n  font-size: 24;\n  font-style: normal;\n  font-weight: normal;\n  color: #fff;\n  background-color: #007eff;\n  text-align: center;\n  text-decoration: none;\n  width: 100%;\n  height: auto;\n  padding: 12px;\n  border-color: #051B2C;\n  border-radius: 4px;\n  border-style: solid;\n  border-width: 0px;\n  box-shadow:\n    0px\n    0px\n    0px\n    0px\n    #051B2C;\n  margin-top: 0px;\n  margin-right: 0px;\n  margin-bottom: 0px;\n  margin-left: 0px;\n}\n.close-button-c744c5de-c0e4-4efe-86a3-75a0e18fc890 {\n    \n        top: -8px;\n        right: -8px;\n    \n    min-width: 48px;\n    min-height: 48px;\n    position: absolute;\n    \n        display: flex;\n    \n    justify-content: center;\n    flex-direction: column;\n    align-items: center;\n    z-index: 2;\n    margin-top: 0px;\n    margin-right: 0px;\n    margin-bottom: 0px;\n    margin-left: 0px;\n}\n\n.close-button-c744c5de-c0e4-4efe-86a3-75a0e18fc890 \u003e svg,\n.close-button-c744c5de-c0e4-4efe-86a3-75a0e18fc890 \u003e img {\n    width: 10px;\n    height: 10px;\n}\n#5869698d-9b45-40bf-a02f-5bb5aab8041f {\n  font-size: 18px;\n  color: #999;\n  margin-top: 0px;\n  text-align: center;\n}\n\n        \n    \u003c/style\u003e\n    \u003cscript\u003e\n        function setSafeAreaInsets({ top, bottom, right, left }) {\n            document.documentElement.style.setProperty('--safe-area-inset-top', `${top}px`);\n            document.documentElement.style.setProperty('--safe-area-inset-bottom', `${bottom}px`);\n            document.documentElement.style.setProperty('--safe-area-inset-right', `${right}px`);\n            document.documentElement.style.setProperty('--safe-area-inset-left', `${left}px`);\n        }\n\n        window.onmessage = function(event) {\n            if (event.data.type === \"set_preview_safe_area_insets\") {\n                setSafeAreaInsets({\n                    top: event.data.safeAreaInsetTop,\n        
2023-08-30 15:34:48.021 27348-28401 OneSignal               com.kyivstar.tv.mobile               D              bottom: event.data.safeAreaInsetBottom,\n                    right: event.data.safeAreaInsetRight,\n                    left: event.data.safeAreaInsetLeft,\n                });\n            }\n        };\n    \u003c/script\u003e\n\u003c/head\u003e\n\u003cbody\u003e\n    \u003cdiv class=\"outer-content-container\"\u003e\n        \n        \u003cdiv class=\"pages-container\"\u003e\n            \n                \u003cdiv\n                    class=\"page page-0 iam-action-templatable\"\n                    data-page-index=\"0\"\n                    data-page-id=\"9655f742-74bd-4735-8340-c4f9e5ae193d\"\n                    data-action-payload='%7B%22close%22%3Afalse%2C%22prompts%22%3A%5B%5D%2C%22url_target%22%3A%22browser%22%2C%22id%22%3A%22e291194a-31f4-4220-9894-0617556f0134%22%7D'\n                \u003e\n                    \u003cdiv class=\"flex-container\"\u003e\n                        \u003cdiv class=\"title-container iam-templatable\"\u003e\n    \u003ch1 id=\"text-dcff8633-5845-4659-be32-3d15cbc7937c\"\u003eTest for adult\u003c/h1\u003e\n\u003c/div\u003e\u003cdiv class=\"button-container\"\u003e\n  \u003cbutton type=\"button\" id=\"button-e76dd4e2-9354-4e3f-9a0c-2789c44afa0a\" class=\"iam-button iam-clickable iam-templatable iam-action-templatable\" data-action-payload='%7B%22close%22%3Atrue%2C%22prompts%22%3A%5B%5D%2C%22url_target%22%3A%22browser%22%2C%22id%22%3A%22d55a1759-733e-43e8-af92-f70ec5226f22%22%7D' data-action-label=\"button\"\u003eClick Me\u003c/button\u003e\n\u003c/div\u003e\n\u003cdiv\n    class=\"close-button close-button-c744c5de-c0e4-4efe-86a3-75a0e18fc890 iam-clickable\"\n    id=\"c744c5de-c0e4-4efe-86a3-75a0e18fc890\"\n    data-action-payload='{\"close\":true,\"prompts\":[],\"url_target\":\"browser\",\"id\":\"33618ac8-5da8-4902-9242-60bcf5a205fa\"}'\n    onclick='actionTaken({\"close\":true,\"prompts\":[],\"url_target\":\"browser\",\"id\":\"33618ac8-5da8-4902-9242-60bcf5a205fa\"}, \"close_button\")'\n    data-action-label=\"close_button\"\n\u003e\n    \n        \u003csvg width=\"10\" height=\"10\" preserveAspectRatio=\"none\" viewBox=\"0 0 8 8\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"\u003e\n            \u003cpath d=\"M7.80309 1.14768C8.06564 0.885137 8.06564 0.459453 7.80309 0.196909C7.54055 -0.0656362 7.11486 -0.0656362 6.85232 0.196909L4 3.04923L1.14768 0.196909C0.885137 -0.0656362 0.459453 -0.0656362 0.196909 0.196909C-0.0656362 0.459453 -0.0656362 0.885137 0.196909 1.14768L3.04923 4L0.196909 6.85232C-0.0656362 7.11486 -0.0656362 7.54055 0.196909 7.80309C0.459453 8.06564 0.885137 8.06564 1.14768 7.80309L4 4.95077L6.85232 7.80309C7.11486 8.06564 7.54055 8.06564 7.80309 7.80309C8.06564 7.54055 8.06564 7.11486 7.80309 6.85232L4.95077 4L7.80309 1.14768Z\" fill=\"#111111\"/\u003e\n        \u003c/svg\u003e\n    \n\u003c/div\u003e\n\n\n                    \u003c/div\u003e\n                \u003c/div\u003e\n            \n        \u003c/div\u003e\n        \n    \u003c/div\u003e\n\u003c/body\u003e\n\u003c/html\u003e\n","display_duration":0,"styles":{"remove_height_margin":false,"remove_width_margin":false}}
2023-08-30 15:34:48.027 27348-28409 OneSignal               com.kyivstar.tv.mobile               D  OneSignal SessionManager onInAppMessageReceived messageId: 78167909-e82f-4c9d-ab1a-63c6ee01876f
2023-08-30 15:34:48.027 27348-28409 OneSignal               com.kyivstar.tv.mobile               D  OneSignal OSChannelTracker for: iam_id saveLastId: 78167909-e82f-4c9d-ab1a-63c6ee01876f
2023-08-30 15:34:48.027 27348-28409 OneSignal               com.kyivstar.tv.mobile               D  OneSignal OSChannelTracker for: iam_id saveLastId with lastChannelObjectsReceived: [{"iam_id":"0eae5c02-1173-4e1b-adc9-447bb41b8a0a","time":1693397044010},{"iam_id":"4a6fe1ee-3e2f-48aa-983f-da4ad2c9569d","time":1693397390274},{"iam_id":"695d125c-bee8-4c42-80c5-27b461390b62","time":1693397449360}]
2023-08-30 15:34:48.028 27348-28409 OneSignal               com.kyivstar.tv.mobile               D  OneSignal OSChannelTracker for: iam_id with channelObjectToSave: [{"iam_id":"0eae5c02-1173-4e1b-adc9-447bb41b8a0a","time":1693397044010},{"iam_id":"4a6fe1ee-3e2f-48aa-983f-da4ad2c9569d","time":1693397390274},{"iam_id":"695d125c-bee8-4c42-80c5-27b461390b62","time":1693397449360},{"iam_id":"78167909-e82f-4c9d-ab1a-63c6ee01876f","time":1693398888027}]
2023-08-30 15:34:48.028 27348-28409 OneSignal               com.kyivstar.tv.mobile               D  OneSignal ChannelTracker getLastReceivedIds lastChannelObjectReceived: [{"iam_id":"0eae5c02-1173-4e1b-adc9-447bb41b8a0a","time":1693397044010},{"iam_id":"4a6fe1ee-3e2f-48aa-983f-da4ad2c9569d","time":1693397390274},{"iam_id":"695d125c-bee8-4c42-80c5-27b461390b62","time":1693397449360},{"iam_id":"78167909-e82f-4c9d-ab1a-63c6ee01876f","time":1693398888027}]
2023-08-30 15:34:48.028 27348-28409 OneSignal               com.kyivstar.tv.mobile               D  OneSignal OSChannelTracker resetAndInitInfluence: iam_id finish with influenceType: INDIRECT
2023-08-30 15:34:48.029 27348-28409 OneSignal               com.kyivstar.tv.mobile               V  OSInAppMessageLifecycleHandler: IAM Will Display: 78167909-e82f-4c9d-ab1a-63c6ee01876f
2023-08-30 15:34:48.038 27348-28409 OneSignal               com.kyivstar.tv.mobile               D  in app message showMessageContent on currentActivity: com.vidmind.android_avocado.feature.main.MainActivity@a5aa50c
2023-08-30 15:34:48.554 27348-28479 OneSignal               com.kyivstar.tv.mobile               D  OSJavaScriptInterface:postMessage: {"type":"rendering_complete","pageMetaData":{},"displayLocation":"full_screen","dragToDismissDisabled":false}
2023-08-30 15:34:48.557 27348-28479 OneSignal               com.kyivstar.tv.mobile               D  In app message activity available currentActivityName: com.vidmind.android_avocado.feature.main.MainActivity lastActivityName: null
2023-08-30 15:34:48.558 27348-28479 OneSignal               com.kyivstar.tv.mobile               D  In app message, showing first one with height: null
2023-08-30 15:34:49.811 27348-27348 OneSignal               com.kyivstar.tv.mobile               V  OSInAppMessageLifecycleHandler: IAM Did Display: 78167909-e82f-4c9d-ab1a-63c6ee01876f
2023-08-30 15:34:49.813 27348-28501 OneSignal               com.kyivstar.tv.mobile               D  OneSignalRestClient: Making request to: https://api.onesignal.com/in_app_messages/78167909-e82f-4c9d-ab1a-63c6ee01876f/impression
2023-08-30 15:34:49.814 27348-28501 OneSignal               com.kyivstar.tv.mobile               D  OneSignalRestClient: POST SEND JSON: {"app_id":"7ef3108d-4ea3-459b-9a10-6c2a3710f401","player_id":"be4f97c3-2e6e-4a76-8b0a-9a9d30d2ae33","variant_id":"e96595e0-ddbd-4b53-9e23-8b3b5dd13f91","device_type":1,"first_impression":true}
2023-08-30 15:34:49.888 27348-28501 OneSignal               com.kyivstar.tv.mobile               V  OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/in_app_messages/78167909-e82f-4c9d-ab1a-63c6ee01876f/impression
2023-08-30 15:34:49.888 27348-28501 OneSignal               com.kyivstar.tv.mobile               D  OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/in_app_messages/78167909-e82f-4c9d-ab1a-63c6ee01876f/impression
2023-08-30 15:34:49.890 27348-28501 OneSignal               com.kyivstar.tv.mobile               D  OneSignalRestClient: POST RECEIVED JSON: {"success":true}
2023-08-30 15:34:49.890 27348-28507 OneSignal               com.kyivstar.tv.mobile               D  Successful post for in-app message impression request: {"success":true}
2023-08-30 15:35:02.427 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  Triggers added: {home_page_open_trigger=13}
2023-08-30 15:35:02.427 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  Starting evaluateInAppMessages
2023-08-30 15:35:02.428 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  displayFirstIAMOnQueue: [OSInAppMessage{messageId='78167909-e82f-4c9d-ab1a-63c6ee01876f', variants={all={default=e96595e0-ddbd-4b53-9e23-8b3b5dd13f91}}, triggers=[[OSTrigger{triggerId='1b7d043e-1e3c-4b75-bd39-be0cb8122977', kind=custom, property='profile_type', operatorType=equal, value=Adult_profile}, OSTrigger{triggerId='588ced24-ff17-4e12-8d23-94d8ece8bb6c', kind=custom, property='my_video_page_open_trigger', operatorType=greater, value=10}]], clickedClickIds=[], redisplayStats=OSInAppMessageDisplayStats{lastDisplayTime=1693398816, displayQuantity=3, displayLimit=2147483647, displayDelay=0}, displayDuration=0.0, displayedInSession=true, triggerChanged=true, actionTaken=false, isPreview=false, endTime=null, hasLiquid=false}]
2023-08-30 15:35:02.428 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  In app message is currently showing or there are no IAMs left in the queue! isInAppMessageShowing: true
2023-08-30 15:35:03.393 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  Triggers added: {my_video_page_open_trigger=12}
2023-08-30 15:35:03.393 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  Starting evaluateInAppMessages
2023-08-30 15:35:03.394 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  displayFirstIAMOnQueue: [OSInAppMessage{messageId='78167909-e82f-4c9d-ab1a-63c6ee01876f', variants={all={default=e96595e0-ddbd-4b53-9e23-8b3b5dd13f91}}, triggers=[[OSTrigger{triggerId='1b7d043e-1e3c-4b75-bd39-be0cb8122977', kind=custom, property='profile_type', operatorType=equal, value=Adult_profile}, OSTrigger{triggerId='588ced24-ff17-4e12-8d23-94d8ece8bb6c', kind=custom, property='my_video_page_open_trigger', operatorType=greater, value=10}]], clickedClickIds=[], redisplayStats=OSInAppMessageDisplayStats{lastDisplayTime=1693398816, displayQuantity=3, displayLimit=2147483647, displayDelay=0}, displayDuration=0.0, displayedInSession=true, triggerChanged=true, actionTaken=false, isPreview=false, endTime=null, hasLiquid=false}]
2023-08-30 15:35:03.394 27348-27348 OneSignal               com.kyivstar.tv.mobile               D  In app message is currently showing or there are no IAMs left in the queue! isInAppMessageShowing: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @YKyrychenko thank you for reaching out! We are aware of this and currently working on a solution. We'll let you know when an update has been released!

**Comment by jinliu9508** [comment]
This issue has been addressed in our latest User Model 5.x.x version. Please upgrade to the latest version, and let us know if you encounter any further issues.

**Comment by bitsydarel** [comment]
@jennantilla @jinliu9508 This is still happening on the latest version of the Android SDK. Both with back gesture and back navigation button.

Since the back button event is not handled and the removeAllViews is not called in that case.
