### ISSUE TITLE
Crashes on JSONUtils - ConcurrentModificationException

### ISSUE THREAD

**Issue by baole** [OneSignal/OneSignal-Android-SDK#465]
Since the last update, we received a number of reports with following stack track:

```java
java.util.LinkedHashMap$LinkedHashIterator.nextEntry (LinkedHashMap.java:411)
--
  | java.util.LinkedHashMap$KeyIterator.next (LinkedHashMap.java:422)
  | com.onesignal.JSONUtils.generateJsonDiff (JSONUtils.java:33)
  | com.onesignal.UserState.newInstance (UserState.java:267)
  | com.onesignal.UserState.newInstance (UserState.java:102)
  | com.onesignal.UserStateSynchronizer.getId (UserStateSynchronizer.java:162)
  | com.onesignal.UserStateSynchronizer$NetworkHandlerThread$1.run (UserStateSynchronizer.java:65)
  | android.os.Handler.handleCallback (Handler.java:751)
  | android.os.HandlerThread.run (HandlerThread.java:61)
```

**Comment by jkasten2** [comment]
@baole Thanks for reporting we will look into it. If your crash report includes the stack of other threads to please attach or link to this.

Also are you able to reproduce the issue?

**Comment by baole** [comment]
The attachment is a full crash report from Crashlytics. It happened on our production app and I'm not able to reproduce the issue.

[net.tandem_issue_5442_crash_5AA0A768038B00011FCB2ACBB73DC15A_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1792344/net.tandem_issue_5442_crash_5AA0A768038B00011FCB2ACBB73DC15A_DNE_0_v2.txt)

**Comment by jkasten2** [comment]
@baole Thanks for the full log. It's odd that `com.onesignal.UserStateSynchronizer.getId (UserStateSynchronizer.java:162)` isn't matching up with [`3.8.0`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.8.0/OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateSynchronizer.java#L162) or [`3.8.1`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.8.1/OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateSynchronizer.java#L162) of our SDK as `getId` isn't called at this line.

We did add some extra `synchronized` around this method in our [3.8.2](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.8.2/OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStateSynchronizer.java#L157) update however which may have solved this `java.util.ConcurrentModificationException` exception. Can you try this update in the next version of your app and let us know if it helps?

We will still also look a bit deeper into the issue on our side and report back. Thanks!

**Comment by baole** [comment]
We are going to release new version with OneSignal 3.8.2. Keep you posted on how it goes!

**Comment by baole** [comment]
Our latest build with OneSignal 3.8.2 still see the same crashes. Please check the full stacktrack in the attached file.
[net.tandem_issue_5442_crash_5AAB0BA0039100010DDABCDB4FA6504D_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1818513/net.tandem_issue_5442_crash_5AAB0BA0039100010DDABCDB4FA6504D_DNE_0_v2.txt)

**Comment by jkasten2** [comment]
@baole Just created a fixed in the PR above and it will go into the next release. I created a unit test this time to ensure the problem was fixed and to prevent future regression of this issue. We will post a release on this page when it is available
https://github.com/OneSignal/OneSignal-Android-SDK/releases

Thanks!

**Comment by jkasten2** [comment]
@baole [OneSignal SDK 3.8.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.8.3) is now released with this fix!

**Comment by asfdfdfd** [comment]
Bug is still here. Attaching stack traces from 3.8.3.

[com.mirrorai.app_issue_816_crash_5AC9151D0318000144461FDD398CF1FA_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1889927/com.mirrorai.app_issue_816_crash_5AC9151D0318000144461FDD398CF1FA_DNE_0_v2.txt)

[com.mirrorai.app_issue_816_crash_5ACB392401E800013A009EF9D799E07D_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1889928/com.mirrorai.app_issue_816_crash_5ACB392401E800013A009EF9D799E07D_DNE_0_v2.txt)

**Comment by jkasten2** [comment]
@asfdfdfd Thanks for the logs, both include the following stack trace.

```java
#0. Crashed: FocusHandlerThread
       at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
       at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
       at com.onesignal.JSONUtils.generateJsonDiff(JSONUtils.java:33)
       at com.onesignal.UserState.generateJsonDiff(UserState.java:267)
       at com.onesignal.UserState.generateJsonDiff(UserState.java:102)
       at com.onesignal.UserStateSynchronizer.persist(UserStateSynchronizer.java:138)
       at com.onesignal.OneSignalStateSynchronizer.persist(OneSignalStateSynchronizer.java:51)
       at com.onesignal.OneSignal.scheduleSyncService(OneSignal.java:997)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:975)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:171)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

We will look into reproducing this issue and providing an update to fix this. Thanks

**Comment by jkasten2** [comment]
@asfdfdfd This occurrence has now been fixed in the 3.8.4 update>
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.8.4
