### ISSUE TITLE
Android 6.0.1 crashed when receive In-App Messaging 

### ISSUE THREAD

**Issue by rgomezp** [OneSignal/OneSignal-Android-SDK#930]
**Description:**
App crashed in particular Android devices when trying to display OneSignal in-app messaging. 

Reported here:
https://github.com/OneSignal/react-native-onesignal/issues/895
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/260

**Environment**

Android 6.0.1

**Stack Traces**
```
01-09 11:05:54.096  #18281-18377/com.google.firebase.unity.analytics.testapp I/OneSignal: Device registered, UserId = 9f2d2e85-57f8-407f-a670-1ba8004b6e69
01-09 11:06:06.346 18281-18396/com.google.firebase.unity.analytics.testapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-09 11:06:06.346 18281-18396/com.google.firebase.unity.analytics.testapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-09 11:06:06.546 18281-18281/com.google.firebase.unity.analytics.testapp I/WebViewFactory: Loading com.google.android.webview version 79.0.3945.93 (code 394509305)
01-09 11:06:06.666 18281-18281/com.google.firebase.unity.analytics.testapp I/cr_LibraryLoader: Time to load native libraries: 1 ms
01-09 11:06:06.746 18281-18281/com.google.firebase.unity.analytics.testapp I/chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
01-09 11:06:06.756 18281-18281/com.google.firebase.unity.analytics.testapp I/cr_LibraryLoader: Expected native library version number "79.0.3945.93", actual native library version number "79.0.3945.93"
01-09 11:06:06.826 18281-18281/com.google.firebase.unity.analytics.testapp I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
01-09 11:06:06.996 18281-18281/com.google.firebase.unity.analytics.testapp D/ConnectivityManager: requestNetwork; getAppId(CallingUid) : 10010, CallingPid : 18281
01-09 11:06:07.076 18281-18281/com.google.firebase.unity.analytics.testapp D/ConnectivityManager: requestNetwork; getAppId(CallingUid) : 10010, CallingPid : 18281
01-09 11:06:07.146 18281-18415/com.google.firebase.unity.analytics.testapp W/cr_media: Requires BLUETOOTH permission
01-09 11:06:07.156 18281-18425/com.google.firebase.unity.analytics.testapp E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
01-09 11:06:07.156 18281-18425/com.google.firebase.unity.analytics.testapp D/libEGL: eglInitialize EGLDisplay = 0x8e45f4b4
01-09 11:06:07.276 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/mpeg-L1
01-09 11:06:07.276 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/mpeg-L2
01-09 11:06:07.286 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/x-ms-wma
01-09 11:06:07.286 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/x-ima
01-09 11:06:07.296 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/evrc
01-09 11:06:07.296 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/qcelp
01-09 11:06:07.296 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
01-09 11:06:07.316 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/amr-wb-plus
01-09 11:06:07.316 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/qcelp
01-09 11:06:07.316 18281-18425/com.google.firebase.unity.analytics.testapp W/AudioCapabilities: Unsupported mime audio/evrc
01-09 11:06:07.336 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/wvc1
01-09 11:06:07.346 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/x-ms-wmv
01-09 11:06:07.356 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
01-09 11:06:07.356 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/wvc1
01-09 11:06:07.366 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/x-ms-wmv
01-09 11:06:07.366 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
01-09 11:06:07.366 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
01-09 11:06:07.366 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/mp43
01-09 11:06:07.396 18281-18425/com.google.firebase.unity.analytics.testapp I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
01-09 11:06:07.436 18281-18425/com.google.firebase.unity.analytics.testapp W/VideoCapabilities: Unsupported mime video/sorenson
01-09 11:06:07.766 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:07.766 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:07.786 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:07.786 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:07.876 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:07.876 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:07.896 18281-18281/com.google.firebase.unity.analytics.testapp I/chromium: [INFO:CONSOLE(51)] "postMessageToNative(): {"type":"rendering_complete","pageMetaData":{"rect":{"height":170.75},"flexContainerRect":{"x":24,"y":24,"width":264,"height":520,"top":24,"right":288,"bottom":544,"left":24}},"displayLocation":"center_modal"}", source: data:text/html; charset=utf-8;base64,PGh0bWw+CjxoZWFkPjxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wLCBtYXhpbXVtLXNjYWxlPTEuMCwgdXNlci1zY2FsYWJsZT1ubyIvPgo8c3R5bGU+CiAgICAqIHsKICAgICAgICAtd2Via2l0LXRvdWNoLWNhbGxvdXQ6IG5vbmU7CiAgICAgICAgLXdlYmtpdC11c2VyLXNlbGVjdDogbm9uZTsgLyogRGlzYWJsZSBzZWxlY3Rpb24vY29weSBpbiBVSVdlYlZpZXcgKi8KICAgIH0KICAgIHAgewogICAgICAgIG1hcmdpbi10b3A6IDE2cHg7CiAgICAgICAgbWFyZ2luLWJvdHRvbTogMTZweDsKICAgIH0KICAgIGgxIHsKICAgICAgICBtYXJnaW4tdG9wOiAwOwogICAgICAgIG1hcmdpbi1ib3R0b206IDhweDsKICAgICAgICBmb250LXdlaWdodDogNDAwOwogICAgfQogICAgYm9keSB7CiAgICAgICAgZm9udC1mYW1pbHk6IC1hcHBsZS1zeXN0ZW0sQmxpbmtNYWNTeXN0ZW1Gb250LCJTZWdvZSBVSSIsUm9ib3RvLE94eWdlbi1TYW5zLFVidW50dSxDYW50YXJlbGwsIkhlbHZldGljYSBOZXVlIixzYW5zLXNlcmlmOwogICAgICAgIHBhZGRpbmc6IDE2cHg7CiAgICAgICAgb3ZlcmZsb3c6IGhpZGRlbjsKICAgICAgICBjdXJzb3I6IHBvaW50ZXI7YmFja2dyb3VuZC1pbWFnZTogdXJsKGh0dHBzOi8vd3d3LmZpbGVwaWNrZXIuaW8vYXBpL2ZpbGUvRnd2MlloMDZTSXlKTXBVaFJNemcpOwogICAgICAgICAgICBiYWNrZ3JvdW5kLXBvc2l0aW9uOiBjZW50ZXI7CiAgICAgICAgICAgIGJhY2tncm91bmQtcmVwZWF0OiBuby1yZXBlYXQ7CiAgICAgICAgICAgIGJhY2tncm91bmQtc2l6ZTogY292ZXI7YmFja2dyb3VuZC1jb2xvcjogI2ZmZmZmZjsKICAgICAgICAKICAgIH0KCiAgICAuZmxleC1jb250YWluZXIgewogICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsKICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICB9CgogICAgLyogSW1hZ2Ugb25seSBmb3IgRnVsbHNjcmVlbiBhbmQgTW9kYWwgKi8KICAgIC5pbWFnZS1jb250YWluZXIgewogICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsKICAgIH0KPC9zdHlsZT4KPHNjcmlwdD4KICAgIC8vIENhbGxlZCBmcm9tIG9uQ2xpY2sgb2YgaW1hZ2VzLCBidXR0b25zLCBhbmQgZGlzbWlzcyBidXR0b24KICAgIGZ1bmN0aW9uIGFjdGlvblRha2VuKGRhdGEsIGNsaWNrVHlwZSkgewogICAgICAgIGNvbnNvbGUubG9nKCJhY3Rpb25UYWtlbigpOiAiICsgSlNPTi5zdHJpbmdpZnkoZGF0YSkpOwogICAgICAgIGlmIChjbGlja1R5cGUpCiAgICAgICAgICAgIGRhdGFbImNsaWNrX3R5cGUiXSA9IGNsaWNrVHlwZTsKICAgICAgICBwb3N0TWVzc2FnZVRvTmF0aXZlKHsgdHlwZTogImFjdGlvbl90YWtlbiIsIGJvZHk6IGRhdGEgfSk7CiAgICB9CgogICAgZnVuY3Rpb24gcG9zdE1lc3NhZ2VUb05hdGl2ZShtc2dKc29uKSB7CiAgICAgICAgY29uc29sZS5sb2coInBvc3RNZXNzYWdlVG9OYXRpdmUoKTogIiArIEpTT04uc3RyaW5naWZ5KG1zZ0pzb24pKTsKICAgICAgICB2YXIgZW5jb2RlZE1zZyA9IEpTT04uc3RyaW5naWZ5KG1zZ0pzb24pOwogICAgICAgIHBvc3RNZXNzYWdlVG9Jb3MoZW5jb2RlZE1zZyk7CiAgICAgICAgcG9zdE1lc3NhZ2VUb0FuZHJvaWQoZW5jb2RlZE1zZyk7CiAgICAgICAgcG9zdE1lc3NhZ2VUb0Rhc2hib2FyZChlbmNvZGVkTXNnKTsKICAgIH0KCiAgICBmdW5jdGlvbiBwb3N0TWVzc2FnZVRvSW9zKGVuY29kZWRNc2cpIHsKICAgICAgICAvLyBTZWUgaU9TIFNESyBTb3VyY2UKICAgICAgICAvLyAgICB1c2VyQ29udGVudENvbnRyb2xsZXI6ZGlkUmVjZWl2ZVNjcmlwdE1lc3NhZ2U6CiAgICAgICAgaWYgKHdpbmRvdy53ZWJraXQgJiYgd2luZG93LndlYmtpdC5tZXNzYWdlSGFuZGxlcnMgJiYgd2luZG93LndlYmtpdC5tZXNzYWdlSGFuZGxlcnMuaW9zTGlzdGVuZXIpCiAgICAgICAgICAgIHdpbmRvdy53ZWJraXQubWVzc2FnZUhhbmRsZXJzLmlvc0xpc3RlbmVyLnBvc3RNZXNzYWdlKGVuY29kZWRNc2cpOwogICAgfQoKICAgIGZ1bmN0aW9uIHBvc3RNZXNzYWdlVG9BbmRyb2lkKGVuY29kZWRNc2cpIHsKICAgICAgICBpZiAod2luZG93Lk9TQW5kcm9pZCkKICAgICAgICAgICAgd2luZG93Lk9TQW5kcm9pZC5wb3N0TWVzc2FnZShlbmNvZGVkTXNnKTsKICAgIH0KCiAgICBmdW5jdGlvbiBwb3N0TWVzc2FnZVRvRGFzaGJvYXJkKGVuY29kZWRNc2cpIHsKICAgICAgICBpZiAod2luZG93LnBhcmVudCkgewogICAgICAgICAgICB3aW5kb3cucGFyZW50LnBvc3RNZXNzYWdlKGVuY29kZWRNc2csICIqIik7CiAgICAgICAgfQogICAgfQoKICAgIC8vIGxhc3QtZWxlbWVudCBuZWVkZWQgdG8gZ2l2ZSB0aGUgY29ycmVjdCBoZWlnaHQgZm9yIG1vZGFscyBhbmQgYmFubmVycwogICAgZnVuY3Rpb24gZ2V0UGFnZU1ldGFEYXRhKCkgewogICAgICAgIHZhciBsYXN0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJsYXN0LWVsZW1lbnQiKTsKICAgICAgICBpZiAoIWxhc3RFbGVtZW50KQogICAgICAgICAgICByZXR1cm4ge307CgogICAgICAgIHZhciBmbGV4Q29udGFpbmVyID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiLmZsZXgtY29udGFpbmVyIik7CiAgICAgICAgaWYgKCFmbGV4Q29udGFpbmVyKSB7CiAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoIkNvdWxkIG5vdCBmaW5kIGZsZXgtY29udGFpbmVyIGNsYXNzIHJlcXVpcmVkIHRvIHJlc2l6ZSBtb2RhbCBjb3JyZWN0bHkhIik7CiAgI
01-09 11:06:07.926 18281-18281/com.google.firebase.unity.analytics.testapp D/ViewRootImpl: #1 mView = android.widget.PopupWindow$PopupDecorView{d2dbd22 V.E...... ......I. 0,0-0,0}
01-09 11:06:07.976 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:07.976 18281-18430/com.google.firebase.unity.analytics.testapp E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
01-09 11:06:08.096 18281-18281/com.google.firebase.unity.analytics.testapp W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-09 11:06:08.106 18281-18307/com.google.firebase.unity.analytics.testapp D/libGLESv1: DTS_GLAPI : DTS is not allowed for Package : com.google.firebase.unity.analytics.testapp
01-09 11:06:08.116 18281-18434/com.google.firebase.unity.analytics.testapp E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
01-09 11:06:08.116 18281-18434/com.google.firebase.unity.analytics.testapp E/CRASH: signal 11 (SIGSEGV), code 128 (?), fault addr 00000000
01-09 11:06:08.116 18281-18434/com.google.firebase.unity.analytics.testapp E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-09 11:06:08.116 18281-18434/com.google.firebase.unity.analytics.testapp E/CRASH: Build type 'Development', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
01-09 11:06:08.116 18281-18434/com.google.firebase.unity.analytics.testapp E/CRASH: Build fingerprint: 'samsung/trltexx/trlte:6.0.1/MMB29M/N910FXXU1DRI2:user/release-keys'
01-09 11:06:08.116 18281-18434/com.google.firebase.unity.analytics.testapp E/CRASH: Revision: '0'
```

**Comment by yuji-yoshimura** [comment]
SDK ver: com.onesignal:OneSignal:3.12.6
Device: Samsung GALAXY SC-04F (Android ver 6.0.1)

```
~~~  D/OneSignal: OSJavaScriptInterface:postMessage: {" ~~~
02-07 15:40:54.795 29578-29828/--- E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
02-07 15:40:54.795 29578-29828/--- A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0xe2 in tid 29828 (hwuiTask1)
02-07 15:40:54.895 330-330/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-07 15:40:54.895 330-330/? A/DEBUG: Build fingerprint: 'samsung/SC-04F/SC-04F:6.0.1/MMB29M/SC04FOMU1XQH1:user/release-keys'
02-07 15:40:54.895 330-330/? A/DEBUG: Revision: '13'
02-07 15:40:54.895 330-330/? A/DEBUG: ABI: 'arm'
02-07 15:40:54.895 330-330/? A/DEBUG: pid: 29578, tid: 29828, name: hwuiTask1  >>> --- <<<
02-07 15:40:54.895 330-330/? A/DEBUG: signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xe2
02-07 15:40:54.955 330-330/? A/DEBUG:     r0 00000027  r1 000000e5  r2 00000002  r3 000000e6
02-07 15:40:54.955 330-330/? A/DEBUG:     r4 00000026  r5 00000102  r6 00000001  r7 9815dcf0
02-07 15:40:54.955 330-330/? A/DEBUG:     r8 00000025  r9 9815d070  sl 9815e078  fp 000000de
02-07 15:40:54.955 330-330/? A/DEBUG:     ip 9815de74  sp 000000e3  lr 0000001f  pc b5c03538  cpsr 000f0030
02-07 15:40:54.955 330-330/? A/DEBUG: backtrace:
02-07 15:40:54.955 330-330/? A/DEBUG:     #00 pc 0005f538  /system/lib/libhwui.so
02-07 15:40:54.955 330-330/? A/DEBUG:     #01 pc 0000000d  <unknown>
02-07 15:40:55.205 30109-30109/? E/TZ_CCM_SERVER: Only 'CCM' are supported
02-07 15:40:56.955 887-1334/? E/NativeCrashListener: Exception dealing with report
    android.system.ErrnoException: read failed: EAGAIN (Try again)
        at libcore.io.Posix.readBytes(Native Method)
        at libcore.io.Posix.read(Posix.java:169)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
        at android.system.Os.read(Os.java:367)
        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
```

Does not occur on the emulator, only on the actual machine.
It also seems to occur on other devices, but it is not known exactly because it is not reported to  Firebase Crashlytics.
- BASIO2 SHV36 (Android ver 6.0.1)
- Xperia Z3 SO-01G (Android ver 6.0.1)
- SHARP Aquos 509SH (Android ver 6.0.1)

**Comment by Woffkaa** [comment]
SDK ver 3.12.5 and 3.12.6
Device LG Nexus 5
Android 6.0.1


```02-26 17:32:01.199 2768-3231/com.dev.app_name W/cr_media: Requires BLUETOOTH permission
02-26 17:32:01.202 2768-3245/com.dev.app_name E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
02-26 17:32:01.305 2768-3245/com.dev.app_name W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
02-26 17:32:01.337 2313-2374/? D/bt_btif_gattc: btif_gattc_update_properties BLE device name=HTC BS F8067D len=13 dev_type=2
02-26 17:32:01.366 2768-3245/com.dev.app_name I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
02-26 17:32:01.464 2768-2768/com.dev.app_name I/chromium: [INFO:CONSOLE(48)] "postMessageToNative(): {"type":"rendering_complete","pageMetaData":{"rect":{"height":387.078125},"flexContainerRect":{"x":24,"y":24,"width":264,"height":472,"top":24,"right":288,"bottom":496,"left":24}},"displayLocation":"center_modal"}", source: data:text/html; charset=utf-8;base64,PGh0bWw+CjxoZWFkPjxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wLCBtYXhpbXVtLXNjYWxlPTEuMCwgdXNlci1zY2FsYWJsZT1ubyIvPgo8c3R5bGU+CiAgICAqIHsKICAgICAgICAtd2Via2l0LXRvdWNoLWNhbGxvdXQ6IG5vbmU7CiAgICAgICAgLXdlYmtpdC11c2VyLXNlbGVjdDogbm9uZTsgLyogRGlzYWJsZSBzZWxlY3Rpb24vY29weSBpbiBVSVdlYlZpZXcgKi8KICAgIH0KICAgIHAgewogICAgICAgIG1hcmdpbi10b3A6IDE2cHg7CiAgICAgICAgbWFyZ2luLWJvdHRvbTogMTZweDsKICAgIH0KICAgIGgxIHsKICAgICAgICBtYXJnaW4tdG9wOiAwOwogICAgICAgIG1hcmdpbi1ib3R0b206IDhweDsKICAgICAgICBmb250LXdlaWdodDogNDAwOwogICAgfQogICAgYm9keSB7CiAgICAgICAgZm9udC1mYW1pbHk6IC1hcHBsZS1zeXN0ZW0sQmxpbmtNYWNTeXN0ZW1Gb250LCJTZWdvZSBVSSIsUm9ib3RvLE94eWdlbi1TYW5zLFVidW50dSxDYW50YXJlbGwsIkhlbHZldGljYSBOZXVlIixzYW5zLXNlcmlmOwogICAgICAgIHBhZGRpbmc6IDE2cHg7CiAgICAgICAgb3ZlcmZsb3c6IGhpZGRlbjsKICAgICAgICBjdXJzb3I6IHBvaW50ZXI7YmFja2dyb3VuZC1jb2xvcjogI0ZGRkZGRjsKICAgICAgICAKICAgIH0KCiAgICAuZmxleC1jb250YWluZXIgewogICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsKICAgICAgICBoZWlnaHQ6IDEwMCU7CiAgICB9CgogICAgLyogSW1hZ2Ugb25seSBmb3IgRnVsbHNjcmVlbiBhbmQgTW9kYWwgKi8KICAgIC5pbWFnZS1jb250YWluZXIgewogICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsKICAgIH0KPC9zdHlsZT4KPHNjcmlwdD4KICAgIC8vIENhbGxlZCBmcm9tIG9uQ2xpY2sgb2YgaW1hZ2VzLCBidXR0b25zLCBhbmQgZGlzbWlzcyBidXR0b24KICAgIGZ1bmN0aW9uIGFjdGlvblRha2VuKGRhdGEsIGNsaWNrVHlwZSkgewogICAgICAgIGNvbnNvbGUubG9nKCJhY3Rpb25UYWtlbigpOiAiICsgSlNPTi5zdHJpbmdpZnkoZGF0YSkpOwogICAgICAgIGlmIChjbGlja1R5cGUpCiAgICAgICAgICAgIGRhdGFbImNsaWNrX3R5cGUiXSA9IGNsaWNrVHlwZTsKICAgICAgICBwb3N0TWVzc2FnZVRvTmF0aXZlKHsgdHlwZTogImFjdGlvbl90YWtlbiIsIGJvZHk6IGRhdGEgfSk7CiAgICB9CgogICAgZnVuY3Rpb24gcG9zdE1lc3NhZ2VUb05hdGl2ZShtc2dKc29uKSB7CiAgICAgICAgY29uc29sZS5sb2coInBvc3RNZXNzYWdlVG9OYXRpdmUoKTogIiArIEpTT04uc3RyaW5naWZ5KG1zZ0pzb24pKTsKICAgICAgICB2YXIgZW5jb2RlZE1zZyA9IEpTT04uc3RyaW5naWZ5KG1zZ0pzb24pOwogICAgICAgIHBvc3RNZXNzYWdlVG9Jb3MoZW5jb2RlZE1zZyk7CiAgICAgICAgcG9zdE1lc3NhZ2VUb0FuZHJvaWQoZW5jb2RlZE1zZyk7CiAgICAgICAgcG9zdE1lc3NhZ2VUb0Rhc2hib2FyZChlbmNvZGVkTXNnKTsKICAgIH0KCiAgICBmdW5jdGlvbiBwb3N0TWVzc2FnZVRvSW9zKGVuY29kZWRNc2cpIHsKICAgICAgICAvLyBTZWUgaU9TIFNESyBTb3VyY2UKICAgICAgICAvLyAgICB1c2VyQ29udGVudENvbnRyb2xsZXI6ZGlkUmVjZWl2ZVNjcmlwdE1lc3NhZ2U6CiAgICAgICAgaWYgKHdpbmRvdy53ZWJraXQgJiYgd2luZG93LndlYmtpdC5tZXNzYWdlSGFuZGxlcnMgJiYgd2luZG93LndlYmtpdC5tZXNzYWdlSGFuZGxlcnMuaW9zTGlzdGVuZXIpCiAgICAgICAgICAgIHdpbmRvdy53ZWJraXQubWVzc2FnZUhhbmRsZXJzLmlvc0xpc3RlbmVyLnBvc3RNZXNzYWdlKGVuY29kZWRNc2cpOwogICAgfQoKICAgIGZ1bmN0aW9uIHBvc3RNZXNzYWdlVG9BbmRyb2lkKGVuY29kZWRNc2cpIHsKICAgICAgICBpZiAod2luZG93Lk9TQW5kcm9pZCkKICAgICAgICAgICAgd2luZG93Lk9TQW5kcm9pZC5wb3N0TWVzc2FnZShlbmNvZGVkTXNnKTsKICAgIH0KCiAgICBmdW5jdGlvbiBwb3N0TWVzc2FnZVRvRGFzaGJvYXJkKGVuY29kZWRNc2cpIHsKICAgICAgICBpZiAod2luZG93LnBhcmVudCkgewogICAgICAgICAgICB3aW5kb3cucGFyZW50LnBvc3RNZXNzYWdlKGVuY29kZWRNc2csICIqIik7CiAgICAgICAgfQogICAgfQoKICAgIC8vIGxhc3QtZWxlbWVudCBuZWVkZWQgdG8gZ2l2ZSB0aGUgY29ycmVjdCBoZWlnaHQgZm9yIG1vZGFscyBhbmQgYmFubmVycwogICAgZnVuY3Rpb24gZ2V0UGFnZU1ldGFEYXRhKCkgewogICAgICAgIHZhciBsYXN0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJsYXN0LWVsZW1lbnQiKTsKICAgICAgICBpZiAoIWxhc3RFbGVtZW50KQogICAgICAgICAgICByZXR1cm4ge307CgogICAgICAgIHZhciBmbGV4Q29udGFpbmVyID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiLmZsZXgtY29udGFpbmVyIik7CiAgICAgICAgaWYgKCFmbGV4Q29udGFpbmVyKSB7CiAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoIkNvdWxkIG5vdCBmaW5kIGZsZXgtY29udGFpbmVyIGNsYXNzIHJlcXVpcmVkIHRvIHJlc2l6ZSBtb2RhbCBjb3JyZWN0bHkhIik7CiAgICAgICAgICAgIHJldHVybiB7fTsKICAgICAgICB9CgogICAgICAgIC8vIHJlY3QueSB3aWxsIGJlIHVuZGVmaW5lZCBvbiBBbmRyb2lkIDQuNAogICAgICAgIHZhciBmbGV4Q29udGFpbmVyUmVjdCA9IGZsZXhDb250YWluZXIuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7CiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgcmVjdDogewogICAgI
02-26 17:32:01.477 2768-3250/com.dev.app_name E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
02-26 17:32:01.477 2768-3250/com.dev.app_name E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw
02-26 17:32:01.475 1432-1432/? W/Binder_5: type=1400 audit(0.0:41228): avc: denied { ioctl } for path="socket:[311514]" dev="sockfs" ino=311514 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
02-26 17:32:01.475 1432-1432/? W/Binder_5: type=1400 audit(0.0:41229): avc: denied { ioctl } for path="socket:[311514]" dev="sockfs" ino=311514 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
02-26 17:32:01.538 2768-2935/com.dev.app_name E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
02-26 17:32:01.805 779-886/? D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 102]
02-26 17:32:02.233 3262-3262/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 11325 <<<<<<
02-26 17:32:02.238 3262-3262/? D/AndroidRuntime: CheckJNI is OFF
02-26 17:32:02.281 3262-3262/? D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
02-26 17:32:02.349 3262-3262/? I/Radio-JNI: register_android_hardware_Radio DONE
02-26 17:32:02.393 3262-3262/? D/AndroidRuntime: Calling main entry org.chromium.components.crash.browser.CrashpadMain
02-26 17:32:02.443 2313-2374/? D/bt_btif_gattc: btif_gattc_update_properties BLE device name=AI Module_115 len=13 dev_type=2
02-26 17:32:02.471 3262-3262/? E/chromium: [0226/173202.470861:ERROR:elf_dynamic_array_reader.h(61)] tag not found
02-26 17:32:02.512 3262-3262/? W/chromium: [0226/173202.512894:WARNING:process_reader_linux.cc(125)] no stack mapping
02-26 17:32:02.518 3262-3262/? D/AndroidRuntime: Shutting down VM
--------- beginning of crash
02-26 17:32:02.759 2768-2935/com.dev.app_name A/libc: Fatal signal 11 (SIGSEGV), code -6, fault addr 0xad0 in tid 2935 (hwuiTask1)
02-26 17:32:02.813 199-199/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-26 17:32:02.813 199-199/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30X/3237893:user/release-keys'
02-26 17:32:02.814 199-199/? A/DEBUG: Revision: '11'
02-26 17:32:02.814 199-199/? A/DEBUG: ABI: 'arm'
02-26 17:32:02.814 199-199/? A/DEBUG: pid: 2768, tid: 2935, name: hwuiTask1  >>> com.dev.app_name <<<
02-26 17:32:02.817 199-199/? A/DEBUG: signal 7 (SIGBUS), code -6 (SI_TKILL), fault addr 0xe2
02-26 17:32:02.877 199-199/? A/DEBUG:     r0 00000027  r1 000000e5  r2 00000002  r3 000000e6
02-26 17:32:02.878 1889-1617/? W/GmsLocationProvider: Error removing location updates: 16
02-26 17:32:02.878 199-199/? A/DEBUG:     r4 00000026  r5 00000102  r6 00000001  r7 976eacf0
02-26 17:32:02.878 199-199/? A/DEBUG:     r8 00000025  r9 976ea070  sl 976eb078  fp 000000de
02-26 17:32:02.878 199-199/? A/DEBUG:     ip 976eae74  sp 000000e3  lr 0000001f  pc b5dd03f8  cpsr 000f0030
02-26 17:32:02.880 199-199/? A/DEBUG: backtrace:
02-26 17:32:02.881 199-199/? A/DEBUG:     #00 pc 0005a3f8  /system/lib/libhwui.so
02-26 17:32:02.881 199-199/? A/DEBUG:     #01 pc 0000000d  <unknown>
02-26 17:32:03.565 199-199/? W/debuggerd: type=1400 audit(0.0:41230): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6138 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=0
02-26 17:32:04.106 199-199/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_04
02-26 17:32:04.107 199-199/? E/DEBUG: AM write failed: Broken pipe
02-26 17:32:04.115 779-798/? I/BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
02-26 17:32:04.122 779-798/? W/DropBoxManagerService: Dropping: SYSTEM_TOMBSTONE (10 > 0 bytes)
02-26 17:32:04.140 779-3285/? W/ActivityManager:   Force finishing activity com.dev.app_name/-.-.-.-
02-26 17:32:04.149 779-3288/? W/DropBoxManagerService: Dropping: data_app_native_crash (760 > 0 bytes)```

**Comment by qq1341738311** [comment]
I have the same problem and need help. How to solve it?

**Comment by pedrofurtado** [comment]
@rgomezp Thanks for feedback! Is there any planning in what release this fix will be available?

**Comment by mikechoch** [comment]
Have you defined any `configChanges` params in the `AndroidManifest.xml`?
Something that might look like this?
`android:configChanges="...">`

If so what `configChanges` are specified for your applications?

**Comment by anniewey** [comment]
@mikechoch In my case, I'm using
`android:configChanges="keyboard|keyboardHidden|orientation|screenSize"`

**Comment by pedrofurtado** [comment]
@rgomezp I shared the log of device in this issue, to help OneSignal team to provide a solution 🤝 : https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/634

**Comment by piolomartin** [comment]
I have the same problem, waiting for the solution.

**Comment by rgomezp** [comment]
Howdy,
We have implemented a solution for this one and will have it out on the next release. Thanks for your cooperation and patience

**Comment by pedrofurtado** [comment]
@rgomezp Thank you so much for feedback! 🤝

**Comment by jkasten2** [comment]
@pedrofurtado Sorry for the mistake on this issue, we don't have a fix for this yet.

Our update is that we haven't been able to reproduce this crash on an Android 6.0 emulator nor any of the real Android 6.0 we have either. We are looking into getting one of the specific device models  reported here to attempt to reproduce the issue.

**Comment by pedrofurtado** [comment]
@jkasten2 @rgomezp A example device model with this bug: https://comparador.tecmundo.com.br/moto-x-2-geracao

**Comment by technicalsamme** [comment]
i have the same problem. plz fix this issue as soon as possible

**Comment by JellisHogenbijl** [comment]
Has there been any progress on this issue? 
We are experiencing this on multiple Android 6.0 devices and we had to disable the use of OneSignal on Android 6 because the app crashes within a minute of starting up.

- Sony experia z3
- Samsung S5
- NVIDEA Shield K1 tablet

**Comment by ctrlemo** [comment]
Experiencing same issue.
In-App Message TOP, BOTTOM seems to work ok.
But displaying the IAM with CENTER or FULL crashes the App right after, when on Android 6.0

Device
Samsung SM-G800H

**Comment by pedrofurtado** [comment]
@rgomezp any news available for us? :handshake:

**Comment by mikechoch** [comment]
A commonality I am noticing with the stacks is all of these are `arm` devices. Has anyone reproduced this problem or seen it from any other Android devices that are NOT `arm`?

**Comment by rgomezp** [comment]
Howdy everyone.
We have identified the issue as being `getBoundingClientRect` being empty in the event of API23 on `arm` devices. We are continuing to work to resolve this. Thanks for your patience.

**Comment by mikechoch** [comment]
This is fixed in latest Android release 3.15.2

**Comment by pacifio** [comment]
## Samsung android 6.0 crash

I am still facing this issue
<img width="935" alt="Screenshot 2020-08-13 at 8 00 53 AM" src="https://user-images.githubusercontent.com/32670628/90086046-4fcf0e00-dd3b-11ea-80d2-e8f6eb6a9bce.png">

I am using flutter
>pubspec.yaml dependencies
```yaml
  cupertino_icons: ^0.1.2
  http: any
  cached_network_image: any
  simple_moment: any
  ant_icons: any
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: any
  flutter_offline: "^0.3.0"
  connectivity: ^0.4.3+1
  uni_links: any
  url_launcher: ^5.4.5
  shimmer: ^1.1.1
  intl: any
  share: ^0.6.4
  flutter_cache_manager: ^1.2.2
  flutter_gifimage: ^1.0.0
  audioplayers: ^0.15.1
  date_range_picker: ^1.0.5
  onesignal_flutter: ^2.6.0
  carousel_slider: ^2.0.0
```
>build.gradle
```gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.5, 0.99.99]'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
>app/build.gradle
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "MY_APPLICATION_ID"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 10
        versionName "2.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
    
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.onesignal:OneSignal:[3.11.2, 3.99.99]'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

```

I might have some version mismatch or something
experts please help
only happening on android 6.0.1 devices ... ( even on xiaomi devices )

**Comment by pedrofurtado** [comment]
@rgomezp @mikechoch 👍

**Comment by ctrlemo** [comment]
Nice! Thanks 👍🏽

**Comment by pacifio** [comment]
I fixed it by adding firebase cloud messaging
> in app/build.gradle add this
```
implementation 'com.google.firebase:firebase-messaging:20.0.0'
```

**Comment by pedrofurtado** [comment]
> I fixed it by adding firebase cloud messaging
> 
> > in app/build.gradle add this
> 
> ```
> implementation 'com.google.firebase:firebase-messaging:20.0.0'
> ```

Is that serious? 🤣  Oh God! If so, I can test here in our app

**Comment by jkasten2** [comment]
@pacifio @pedrofurtado We confirmed this issue was fixed in [release 3.15.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.15.2) with PR #1105

Do you have OneSignal as a version range or an exact version? If you have a range and change anything in your `build.gradle` file you will have to sync which will auto update to the latest version in the range. So basically resyncing gradle may have auto updated OneSignal.

**Comment by ndmkapps** [comment]
> implementation 'com.google.firebase:firebase-messaging:20.0.0'

Thanks a lot, it worked :)
